version: "3.9"
services:
  server:
    build: 
      dockerfile: Dockerfile.server
      context: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ../DataFiles:/DataFiles
  client:
    depends_on:
      - server
    build: 
      dockerfile: Dockerfile.client
      context: .
