# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/proto.proto\"!\n\x0eStringResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0b\x46ileMessage\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x32i\n\x07Greeter\x12-\n\nUploadFile\x12\x0c.FileMessage\x1a\x0f.StringResponse\"\x00\x12/\n\x0c\x44ownloadFile\x12\x0f.StringResponse\x1a\x0c.FileMessage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRINGRESPONSE._serialized_start=22
  _STRINGRESPONSE._serialized_end=55
  _FILEMESSAGE._serialized_start=57
  _FILEMESSAGE._serialized_end=90
  _GREETER._serialized_start=92
  _GREETER._serialized_end=197
# @@protoc_insertion_point(module_scope)
